version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poke-rpa-backend
    ports:
      - "8001:8001"
    # volumes:
    #   - .:/app  # Removido para evitar sobrescrita e problemas de permissão em produção
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: poke-rpa-frontend
    ports:
      - "80:80"  # Porta padrão do Nginx para acesso mais simples
    depends_on:
      - backend
