version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poke-rpa-backend
    ports:
      - "8001:8001"
    volumes:
      - .:/app  # Ativado para desenvolvimento: arquivos gerados no container aparecem no host
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: poke-rpa-frontend
    ports:
      - "80:80"  # Porta padrão do Nginx para acesso mais simples
    depends_on:
      - backend
