version: '3.8'
services:
  poke-rpa-pipeline:
    build: .
    container_name: poke-rpa-pipeline
    volumes:
      - ./data:/app/data
      - ./chat_outputs:/app/chat_outputs
      - ./logs:/app/logs
      - ./erro.txt:/app/erro.txt
      - ./planejamento.txt:/app/planejamento.txt
    command: ["python", "main.py", "chat"] # Pode ser alterado para "pipeline" ou outros comandos
    # environment:
    #   - YOUR_ENV_VAR=your_value # Exemplo de variável de ambiente, se necessário 
  frontend:
    build: ./frontend
    container_name: poke-rpa-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Garante que node_modules seja um volume separado para evitar problemas de permissão
    depends_on:
      - poke-rpa-pipeline # O frontend depende do backend para a API 